project:
  type: book
  output-dir: docs

website:
  site-url: https://aayushmnit.com/pytorch_book
  repo-url: https://github.com/aayushmnit/pytorch_book

book:
  title: "The Pytorch Book"
  author: "Aayush Agrawal"
  date: "12/3/2022"
  cover-image: bookcover.jpg
  chapters:
    - index.qmd
    - part: "Pytorch basics"
      chapters: 
        - basics/0_pytorch_intro.ipynb
  

bibliography: references.bib

format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    mainfont: Roboto
  pdf:
    documentclass: scrreprt



