project:
  type: book
  output-dir: docs

website:
  site-url: https://aayushmnit.com/pytorch_book
  repo-url: https://github.com/aayushmnit/pytorch_book

book:
  title: "The PyTorch Book"
  author: "Aayush Agrawal"
  search: true
  sharing: [linkedin, twitter, facebook]
  #date: "12/24/2022"
  cover-image: bookcover.jpg
  google-analytics: "G-Q8J05XS7Q7"
  page-footer: 
    left: "The PyTorch book. Copyright (c) 2022 Aayush Agrawal."
    right: "This book was built with [Quarto](https://quarto.org/)"
  chapters:
    - index.qmd
    - part: "PyTorch basics"
      chapters: 
        - nbs/1_pytorch_intro.ipynb
        - nbs/2_pytorch_tensors.ipynb
        - nbs/3_broadcasting.ipynb
        - nbs/4_autograd.ipynb
        - nbs/5_datasets.ipynb
        - nbs/6_optimizers.ipynb
        - nbs/7_defining_models.ipynb
        - nbs/8_NeuralNetworks.ipynb
    - part: "fastai"
      chapters:
        - nbs/9_IntroductionToFastAI.ipynb
        - nbs/10_MNISTusingFastaiHighLevelAPI.ipynb
        - nbs/11_MNISTusingFastaiMidLevelAPI.ipynb
  

bibliography: references.bib

format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    highlight-style: 
      light: a11y
      dark: github
    mainfont: roboto



