project:
  type: book
  output-dir: docs

website:
  site-url: https://aayushmnit.com/pytorch_book
  repo-url: https://github.com/aayushmnit/pytorch_book

book:
  title: "The PyTorch Book"
  author: "Aayush Agrawal"
  search: true
  sharing: [linkedin, twitter, facebook]
  #date: "12/24/2022"
  cover-image: bookcover.jpg
  page-footer: 
    left: "The PyTorch book. Copyright (c) 2022 Aayush Agrawal."
    right: "This book was built with [Quarto](https://quarto.org/)"
  chapters:
    - index.qmd
    - part: "PyTorch basics"
      chapters: 
        - basics/0_pytorch_intro.ipynb
  

bibliography: references.bib

format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    mainfont: Roboto



